spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shop?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: shop_user
    password: shop_user
  jpa:
    database-platform: "org.hibernate.dialect.MySQL8Dialect"
    show-sql: true
  liquibase:
    change-log: "classpath:/liquibase/liquibase-changeLog.xml"

springdoc:
  swagger-ui:
    path: swagger.html
